---
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Compile TypeScript files
          command: ./node_modules/typescript/bin/tsc
      - run:
          name: Stage deploy
          command: ./stage-deploy.sh
      - persist_to_workspace:
          root: _deploy
          paths:
            - site
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c0:bf:83:1f:d6:95:2d:94:ea:8d:4b:d8:2b:2e:06:46"
      - attach_workspace:
          at: _deploy
      - run:
          name: Deploy GitHub Pages
          command: ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
