---
name: deploy-pages
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Compile TypeScript files
        run: ./node_modules/typescript/bin/tsc
      - name: Stage deploy
        run: ./stage-deploy.sh
